In [1]:
import numpy as np
import torch
from numpy import linalg as LA

In [2]:
arr = np.random.randn(4, 5)
arr

array([[ 0.20383288,  1.75557777,  0.52428195, -0.04558229, -0.44687874],
       [-0.05549705, -2.26703378, -0.12188655,  0.18247987,  0.22043993],
       [ 0.63630981,  0.70558821, -2.07699932, -0.88472135,  0.21372526],
       [ 0.97902323, -0.312705  , -0.73630494,  1.17942649, -1.21349863]])

In [4]:
l2_norm = LA.norm(arr, axis=-1, keepdims=True)
l2_norm

array([[1.89743276],
       [2.2889454 ],
       [2.45867473],
       [2.11235452]])

In [5]:
arr_normalized = arr / l2_norm
arr_normalized

array([[ 0.10742561,  0.92523846,  0.27631121, -0.02402314, -0.23551756],
       [-0.02424569, -0.9904272 , -0.05325009,  0.07972225,  0.09630633],
       [ 0.25880195,  0.28697908, -0.84476376, -0.35983668,  0.08692702],
       [ 0.46347487, -0.14803623, -0.34857072,  0.55834685, -0.57447678]])

In [9]:
t = torch.from_numpy(arr)
t_normalized = torch.nn.functional.normalize(t, p=2.0, dim=-1)
t_normalized

tensor([[ 0.1074,  0.9252,  0.2763, -0.0240, -0.2355],
        [-0.0242, -0.9904, -0.0533,  0.0797,  0.0963],
        [ 0.2588,  0.2870, -0.8448, -0.3598,  0.0869],
        [ 0.4635, -0.1480, -0.3486,  0.5583, -0.5745]], dtype=torch.float64)